### ISSUE TITLE
When I copy the url into a new window the graphs fail to load.

### ISSUE THREAD

**Issue by PaulMcManus23** [ostreifel/vsts-contributions#15]
Repro steps: 
- open page in Chrome Version 66.0.3359.139
- open filters section
- add 12 users to the filter
- select all projects
- select commits and changesets
- add all 48 repositories
- note that all graphs load
- copy url
- paste url into new tab

Expected outcome: All the graphs load

Actual outcome: The spinners run for a long time.... then some of the graphs fail to load

Note:
There are maybe 4000 exceptions in the console... that look roughly like this...

Failed to load resource: the server responded with a status of 404 ()

https://<account name>.visualstudio.com/<project name>/_apis/tfvc/changesets?$skip=500&$top=100&searchCriteria%5Bauthor%5D=<email address>

{"$id":"1","innerException":null,"message":"VS403405: The item $/<project name> does not exist on the server, or you do not have permission to access it.","typeName":"Microsoft.TeamFoundation.VersionControl.Server.ItemNotFoundException, Microsoft.TeamFoundation.VersionControl.Server","typeKey":"ItemNotFoundException","errorCode":0,"eventId":4001}

The projects would appear to be git ones that are coming back with 404 for the tfvc query

**Comment by ostreifel** [comment]
404 errors for tfvc requests are [being handled](https://github.com/ostreifel/vsts-contributions/blob/master/scripts/data/tfvc/changsets.ts#L38) and are not the cause of the error. I am able to copy paste  a link that has 404 tfvc links and have the graphs load.

1. Are there any script errors in the console?
2. Can you repo the same thing but for one user so that it is easier to comb though the data for the root issue?
3. Is this only for cross project queries or can you repro it with just one particular project?
4. Does one user/proj combo yield a weird data that throws an exception?

**Comment by ostreifel** [comment]
Please reopen if more information becomes available.
