### ISSUE TITLE
AD identity search and Pull Request (Created/Closed) results are incorrect.

### ISSUE THREAD

**Issue by stedelen** [ostreifel/vsts-contributions#26]
@ostreifel 

Referencing issue #17  and the following workaround for Active Directory (AD) group members:
https://github.com/ostreifel/vsts-contributions/commit/603c161e3496b073787e240ea0eb4a0629f22d37

Is there anyway to present AD group members as an suggestion in the activity filter?  It would help tremendously if we did not have to type out the entire user's name or email.

With the workaround previously committed, the created and closed Pull request counts are incorrect when the filter is applied. As a test, when I added 2 of my AD group members to the team as an explicitly mentioned member, the PR created and closed counts' were correct.

Please help if you can, I would appreciate this.

**Comment by stedelen** [comment]
@ostreifel Providing more information about the incorrect pull request counts and commit #603c161:
There are currently 80 repositories and over 50 teams in our Azure Devops Projects.  

When I enter in a user's email as a workaround for the name suggestion (we use Active Directory), I see that every team member in the activity filter has 344 pull requests.  

Looking further, every pull request for all repositories (since last November) that our team has committed to in our project. When I remove all team members from the activity filter and leave only 1 I still see 344 created pull requests (same count for closed pull request filter)

I temporarily added an existing (very active) team member (referenced by the AD member group) to the team config and he was suggested when I searched for his identity...after selecting his name, he then displays 54 pull requests for the single repository he has been working in. This is correct.

I think incorporating the members from Active Directory into the suggestions from an identity search would solve 2 issues - the created and closed PR contributions and the team member suggestion box (activity filter).

**Comment by ostreifel** [comment]
There appears to be an [api](https://docs.microsoft.com/en-us/rest/api/azure/devops/graph/memberships/list?view=azure-devops-rest-5.0) that almost does this but the client libraries are not currently working - see attached commit for details
![image](https://user-images.githubusercontent.com/5203542/57198226-3e3a6c00-6f25-11e9-88d3-f75f231d1366.png)
The problem is that the client does not seem to consider that the graph apis are hosted on a different domain from the project. Even if the client did consider that the CORS header is not being set in those apis so the browser would just block the request. I can't find any [examples](https://github.com/search?q=%22VSS%2FGraph%2FRestClient%22&type=Code) of this api being used on github either.

To unblock this feature the CORS header in the Graph Apis and graph api client libraries need to be updated by the Azure Devops team.

**Comment by stedelen** [comment]
@ostreifel 

The api you have added as part of #be33f3e  (scripts/data/identities/getGraphIdentities.ts), is there another API that you could reference? Else, do you have to raise this as a feature request in the ms developer community for Azure Devops or is there a better approach?

**Comment by ostreifel** [comment]
This has actually been an issue I've had as an extension author for a while now. Using a teams as a workaround for identities mostly works - it just doesn't expand groups. The only identity api's for extensions that I know of are the teams apis.

There is technically an identity picker api for extensions but its so buggy/undocumented that its not worth using. A product change to make this supported would be most likely be to make that picker work.

**Comment by stedelen** [comment]
@ostreifel Would you create a feature request for the product change and provide a link please? I would like to see a follow-up on behalf of the product team.

**Comment by stedelen** [comment]
@ostreifel  Were you able to add a feature request in the developer community?  Has anyone from the product team reached out about this issue?

**Comment by pabrams** [comment]
> @ostreifel Were you able to add a feature request in the developer community? Has anyone from the product team reached out about this issue?

What's stopping you from doing this yourself?
