### ISSUE TITLE
Chart does not update when there is a lot of data

### ISSUE THREAD

**Issue by dparvin** [ostreifel/vsts-contributions#5]
My TFS system has 40k+ work items and 10k+ change sets and this page will sit looking at them for hours without showing anything.  I have it on a small site and it shows great, Looks very helpful, but on a large site it is no where near fast.

**Comment by ostreifel** [comment]
I had created a stress test environment for the extension but it was not to that magnitude and all from one user. I'll put something together and see where I can find some speedups.

**Comment by dparvin** [comment]
I am a team member of a fairly small team, but we have been putting stuff into TFS for over 5 years so there is a lot of data there.

**Comment by ostreifel** [comment]
So my environment is setup. I think the root cause is that I did not account for users who have more than 20000 workitems in one year. The changesets should work right now but are really slow for that many because of a tradeoff I didn't think would ever get to this point.

I'll try to get
- \> 20k wi
- perf for many many changsets

patched soon

**Comment by ostreifel** [comment]
version 1.6.19 should fix the issues you mentioned. The changesets in particular are making the loading really slow.
Getting 50k wi and 10k revisions takes 2 minutes in my test but almost the entirety of that is retrieving the changesets.
